import os
import re
import sys
import json
import subprocess
from pathlib import Path
import google.generativeai as genai
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor

# Define a premium, modern design theme palette
COLOR_BG = RGBColor(15, 23, 42)       # Slate 900
COLOR_TITLE = RGBColor(56, 189, 248)   # Sky Blue
COLOR_BODY = RGBColor(226, 232, 240)   # Slate 200
COLOR_SUBTITLE = RGBColor(148, 163, 184) # Slate 400

class PPTGeneratorSkill:
    def __init__(self, gemini_api_key: str = None):
        self.gemini_api_key = gemini_api_key
        if gemini_api_key:
            genai.configure(api_key=gemini_api_key)

    def parse_command(self, text: str) -> dict:
        """Detect intent and extract PPT topic and slide count."""
        text_lower = text.lower().strip()
        
        # Regex to detect if command is asking to create a presentation
        match_intent = re.search(r"\b(create|make|generate|build|design|write)\s+(?:a\s+)?(?:new\s+)?(ppt|powerpoint|presentation|slides)\b", text_lower)
        if not match_intent and "ppt" not in text_lower and "presentation" not in text_lower:
            return {"intent": None, "topic": None, "slide_count": 0}
            
        # Extract number of slides if mentioned
        slide_match = re.search(r"(\d+)\s*(slide|page|ppt)", text_lower)
        slide_count = int(slide_match.group(1)) if slide_match else 5  # default to 5 slides
        
        # Extract the topic by removing typical command verbs and stop words
        clean_text = re.sub(
            r"\b(create|make|generate|build|design|write|a|an|new|ppt|powerpoint|presentation|slides|on|about|of|for|topic)\b",
            "",
            text_lower
        )
        # Strip punctuation and double spaces
        clean_text = re.sub(r"\s+", " ", clean_text).strip()
        topic = clean_text.title() if clean_text else "General Knowledge"
        
        return {
            "intent": "create_ppt",
            "topic": topic,
            "slide_count": slide_count
        }

    def generate_content(self, topic: str, slide_count: int) -> list:
        """Fetch structured slide content using Gemini LLM or fallback mock generator."""
        if not self.gemini_api_key:
            print("[PPT Skill] No Gemini API key found. Generating fallback template content.")
            return self._get_fallback_content(topic, slide_count)
            
        prompt = f"""
        You are a professional PowerPoint builder. Create a structured outline for a presentation with {slide_count} slides on the topic: "{topic}".
        Return ONLY a JSON array of objects representing slides.
        Do not include markdown tags like ```json or ```. Return pure JSON.
        
        JSON Structure:
        [
          {{
            "title": "Slide Title Here",
            "bullets": ["Bullet point 1 detailing a key fact", "Bullet point 2 with another important detail", "Bullet point 3 showing a conclusion"]
          }}
        ]
        """
        try:
            model = genai.GenerativeModel("gemini-2.0-flash")
            response = model.generate_content(prompt)
            clean_json = response.text.replace("```json", "").replace("```", "").strip()
            return json.loads(clean_json)
        except Exception as e:
            print(f"[PPT Skill] Gemini content generation failed: {e}. Falling back to default templates.")
            return self._get_fallback_content(topic, slide_count)

    def _get_fallback_content(self, topic: str, slide_count: int) -> list:
        slides = []
        # Cover Slide
        slides.append({
            "title": topic,
            "bullets": [f"Overview of {topic}", "Generated by Sunday AI Assistant", "Powered by python-pptx"]
        })
        # Outline / Content Slides
        for i in range(1, slide_count):
            slides.append({
                "title": f"Key Area {i}: Introduction to {topic}",
                "bullets": [
                    f"Fundamental concept number {i} regarding the core domain.",
                    "Practical applications and modern-day examples in the industry.",
                    "Summary of key challenges, limitations, and future outlook."
                ]
            })
        return slides

    def build_pptx_file(self, topic: str, slides_content: list) -> str:
        """Builds a styled PPTX file and returns the absolute file path."""
        prs = Presentation()
        
        # 1. Slide 1: Title Slide (Layout index 0)
        title_layout = prs.slide_layouts[0]
        slide = prs.slides.add_slide(title_layout)
        
        # Set background solid slate color
        background = slide.background
        fill = background.fill
        fill.solid()
        fill.fore_color.rgb = COLOR_BG
        
        # Style Title
        title_shape = slide.shapes.title
        title_shape.text = topic
        for p in title_shape.text_frame.paragraphs:
            p.font.name = "Segoe UI"
            p.font.size = Pt(46)
            p.font.bold = True
            p.font.color.rgb = COLOR_TITLE
            
        # Style Subtitle
        subtitle_shape = slide.placeholders[1]
        subtitle_shape.text = "Generated by Sunday AI Assistant\nPowered by python-pptx & Gemini"
        for p in subtitle_shape.text_frame.paragraphs:
            p.font.name = "Segoe UI"
            p.font.size = Pt(20)
            p.font.color.rgb = COLOR_SUBTITLE

        # 2. Add content slides
        content_layout = prs.slide_layouts[1]
        for slide_data in slides_content:
            # Avoid duplicating the title slide content if present in the content array
            if slide_data.get("title").lower() == topic.lower():
                continue
                
            slide = prs.slides.add_slide(content_layout)
            
            # Set background
            slide.background.fill.solid()
            slide.background.fill.fore_color.rgb = COLOR_BG
            
            # Slide Title
            t_shape = slide.shapes.title
            t_shape.text = slide_data.get("title", "Overview")
            for p in t_shape.text_frame.paragraphs:
                p.font.name = "Segoe UI"
                p.font.size = Pt(36)
                p.font.bold = True
                p.font.color.rgb = COLOR_TITLE
                
            # Slide Bullet Points
            b_shape = slide.placeholders[1]
            tf = b_shape.text_frame
            tf.clear()
            
            bullets = slide_data.get("bullets", [])
            for idx, text in enumerate(bullets):
                p = tf.add_paragraph() if idx > 0 else tf.paragraphs[0]
                p.text = text
                p.level = 0
                p.space_after = Pt(14)
                p.font.name = "Segoe UI"
                p.font.size = Pt(18)
                p.font.color.rgb = COLOR_BODY

        # Save to user Documents folder
        docs_dir = os.path.join(os.path.expanduser("~"), "Documents")
        os.makedirs(docs_dir, exist_ok=True)
        
        safe_name = re.sub(r'[\\/*?:"<>|]', "", topic).replace(" ", "_")
        file_path = os.path.join(docs_dir, f"{safe_name}_Presentation.pptx")
        
        prs.save(file_path)
        return file_path

    def launch_powerpoint(self, file_path: str):
        """Open the generated file in PowerPoint on Windows."""
        if not os.path.exists(file_path):
            raise FileNotFoundError(f"File not found: {file_path}")
            
        if sys.platform == "win32":
            os.startfile(file_path)
        else:
            opener = "open" if sys.platform == "darwin" else "xdg-open"
            subprocess.Popen([opener, file_path])
